object TailRecursion extends App {

    // Recursive function of tail recursion
    def factorial(n: BigInt): BigInt = {
        def factorialAcc(acc: BigInt, n: BigInt): BigInt = {
            if (n <= 1) acc
            else factorialAcc(n * acc, n - 1)
        }
        factorialAcc(1, n)
    }

    val num1 = 100
    val num2 = 100000

    println("Factorial of " + num1 + " : = " + factorial(num1)) // Factorial of 100 : = 9332621544394415......
    // StackOverflow is not generated by compiling to while.
    println("Factorial of " + num2 + " : = " + factorial(num2)) // Factorial of 100000 : = 2824229407960347......

}


// =====================================
//         Output Sample
// =====================================
// $ scalac TailRecursion.scala 
// $ scala TailRecursion
// Factorial of 100 : = 9332621544394415......
// Factorial of 100000 : = 2824229407960347......